### ISSUE TITLE
Global Environment Variables

### ISSUE THREAD

**Issue by TrevorMadison-PBR** [samterfa/rpysheets#1]
Hello,

Thank you so much for your helpful articles of using R and Python with Google Sheets. I've been greatly helped by this repo and what you've written. I have a quick question that has more to do with docker, but I haven't been able to find a good solution online.

I would like for a couple variables in my global environment to be built in whenever the package deploys. For example, I have a variable that's a model I've created. I only want to use the ```predict()``` function without having to re-create the model each time I hit the API. Is there a way that I can pass along the model that's in the global environment to cr_deploy_run?

I think the issue is that I need to change the ```FROM``` in the Dockerfile since it's samterfa/rpysheets right now, but what should I change it to? What does samterfa/rpysheets reference?

Any advice greatly appreciated. Thanks

**Comment by samterfa** [comment]
I'm glad you've found it useful. In retrospect, I really wish I wouldn't have made custom Docker images for people to follow along with so I understand the confusion.

Within your dockerfile, you could replace FROM samterfa/rmlsheets with FROM rocker/ml-verse or even FROM rocker/tidyverse (see [Rocker repo](https://github.com/rocker-org/rocker-versioned2)).

In your Plumber.R file, any R code or functions you run above the api endpoints themselves will be run on build. This means it will slow down your build but won't slow down a hit of the api. 

Here's an example.

```
#### This section of Plumber.R runs "On Build", or before an api endpoint is hit

# Run "slow" model building code here, and save model "locally".
model <- lm(Sepal.Width ~ Sepal.Length, iris)
readr::write_rds(model, 'iris_model.rds')


#### This section of Plumber.R runs "On Run", or while an api endpoint is hit
#* Predict using a model.
#* @param df The data to predict on.
#* @post /deploymodel
function(df){
  
  # Read in local model object
  model <- readr::read_rds('iris_model.rds')
  
  predict(model, df)
}
```

I'm also a big fan of the [pins package](https://pins.rstudio.com/), so I would be tempted to use a pinned version of a model (stored in Cloud Storage or elsewhere) if it was something I was iteratively developing. Then instead of live building the model, I would simply read the latest pinned version of the model on build (to not slow down the api endpoint). I could then experiment on my local machine, improve the model, and update the model. Technically then you'd have to rebuild your deployed app on Google Cloud, but I think you can also set deployed apps to rebuild on a schedule.

Let me know if any of that didn't make sense.

Sam

**Comment by samterfa** [comment]
Closing the issue for now. Feel free to reopen if you're still having trouble.
